[build]
  publish = "dist"
  command = "npm ci --include=dev && npm run build"

[build.environment]
  NODE_VERSION = "20"

# Deploy from develop branch to staging
[context.deploy-preview]
  command = "npm ci --include=dev && npm run build"

[context.develop]
  command = "npm ci --include=dev && npm run build"

# Production deploy from main
[context.production]
  command = "npm ci --include=dev && npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"