name: Deploy to Production

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run full test suite
      run: npm test -- --coverage --watchAll=false
      
    - name: Run E2E tests
      run: |
        npx playwright install --with-deps
        npx playwright test
      
    - name: Build for production
      run: npm run build
      env:
        NODE_ENV: production
        VITE_APP_ENV: production
        VITE_BUGSNAG_API_KEY: ${{ secrets.VITE_BUGSNAG_API_KEY_PRODUCTION }}
        VITE_ENABLE_ERROR_TRACKING: true
        VITE_ENABLE_PERFORMANCE_MONITORING: true
        VITE_ENABLE_ANALYTICS: true
        
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: './dist'
        production-deploy: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Production deploy from GitHub Actions - ${{ github.sha }}"
        enable-pull-request-comment: false
        enable-commit-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PRODUCTION_SITE_ID }}
        
    - name: Log deployment success
      run: |
        echo "::notice::🚀 Production deployment successful!"
        echo "URL: https://blackjack-simulator.netlify.app"
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref }}"
        
    - name: Run production smoke tests
      run: |
        echo "Running production smoke tests"
        # Add production smoke test commands here
        
    - name: Notify deployment status
      if: always() && vars.SLACK_NOTIFICATIONS_ENABLED == 'true'
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#deployments'
        text: |
          🚀 Production deployment ${{ job.status }}
          Branch: ${{ github.ref }}
          Commit: ${{ github.sha }}
          Author: ${{ github.actor }}
          URL: https://blackjack-simulator.netlify.app
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        
    - name: Log deployment status (No Slack)
      if: always() && vars.SLACK_NOTIFICATIONS_ENABLED != 'true'
      run: |
        echo "::notice::🚀 Production deployment ${{ job.status }}"
        echo "Branch: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"
        echo "Author: ${{ github.actor }}"
        echo "URL: https://blackjack-simulator.netlify.app"
        echo "Consider setting up Slack notifications by configuring SLACK_WEBHOOK_URL secret and SLACK_NOTIFICATIONS_ENABLED variable"